name: StarlingLin
title: StarlingLin | Blog & Shares
description: It's StarlingLin's personal blog! Programming & Others!
tags:
  - blog
  - code
  - programme
  - 博客
  - StarlingLin
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: 2222040903@qq.com
# See: https://disqus.com/
disqus_username: starlinglin
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xdorbnrl
